### ISSUE TITLE
Dependency issue on pip install

### ISSUE THREAD

**Issue by ScottSoren** [SpectroInlets/spectro_inlets_quantification#5]
I've installed spectro_inlets_quantification (siq) v1.2.4 from test-pypi and it works!

The only challenge was that the PyYAML dependency didn't upgrade automatically. pip install fell back to siq v1.2.3 unless I explicitly pip upgraded PyYAML first. This was the case both on my Windows laptop (python 3.9) and my office Debian computer (python 3.11, freshly installed with Anaconda).

In both environments, the following worked:

```
$ pip install --upgrade PyYAML
$ pip install --upgrade -i https://test.pypi.org/simple/ spectro-inlets-quantification
$ pip install --upgrade ixdat
$ python
>>> import ixdat
importing ixdat v0.2.5.dev5 from C:\Users\scott\Anaconda3\lib\site-packages\ixdat\__init__.py
>>> ixdat.plugins.activate_si_quant()
importing spectro_inlets_quantification v1.2.4 from C:\Users\scott\Anaconda3\lib\site-packages\spectro_inlets_quantification\__init__.py
>>> ixdat.plugins.si_quant.Molecule.load("CH4").spectrum
{'M12': 3.8, 'M13': 10.7, 'M14': 20.4, 'M15': 88.8, 'M16': 100.0, 'M17': 1.6}
```

**Comment by KennethNielsen** [comment]
As best I can tell, this is an effect of the package being downloaded from test pypi. I think setting `-i` means that it tries to get all dependencies from there as well and there just is no PyYAML there. Which is also why installing it first works, because then it will get it from the normal pypi.
